# Generated by Django 4.1.5 on 2023-01-25 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=222)),
                ('avatar', models.ImageField(upload_to='feedback/')),
                ('position', models.CharField(max_length=222)),
                ('message', models.TextField()),
            ],
        ),
    ]
